catalog/urls.py
from django.urls import path

from . import views


# General pages
urlpatterns = [
	path("", views.index, name="index"),
	path("accounts/signup", views.UserRegister.as_view(), name="member-signup"),
	path("accounts/profile/<int:pk>", views.UserProfile.as_view(), name="member-profile"),
	path("accounts/<int:uid>/verify/<uuid:token>", views.verifyMemberToken, name="member-verify"),
]


# Books related
urlpatterns += [
	path("books/", views.BookListView.as_view(), name="books"),
	path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
	path("book/create/", views.BookCreate.as_view(), name="book-create"),
	path("book/<int:pk>/update/", views.BookUpdate.as_view(), name="book-update"),
	path("book/<int:pk>/delete/", views.BookDelete.as_view(), name="book-delete"),
]

# Author related
urlpatterns += [
	path("authors/", views.AuthorListView.as_view(), name="authors"),
	path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
	path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
	path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
	path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

# Genre related
urlpatterns += [
	path("genres/", views.GenresListView.as_view(), name="genres"),
	path("genres/<int:pk>", views.genre_details, name="genre-detail"),
]

# User related (functional) [ member and staff]
urlpatterns += [
	path("mybooks/", views.BorrowerListView.as_view(), name="my-borrowed"),
	path("book/<uuid:pk>/borrow/", views.BorrowBook.as_view(), name="borrow-book"),
	path("book/<uuid:pk>/return/", views.return_book, name="return-book"),
	path("borrowed/", views.LibrarianListView.as_view(), name="all-borrowed"),
	path("book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls.static import static

from catalog.forms import CustomAuthForm


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('catalog/', include("catalog.urls")),
    path('catalog/reviews/', include("reviews.urls")),
    path("", RedirectView.as_view(url='catalog/', permanent=True)),
    path("accounts/login/", LoginView.as_view(
                                        redirect_authenticated_user=True,
                                        form_class = CustomAuthForm
                                    ), name="login"),
    path("accounts/", include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_title = "Library"
admin.site.site_header = "Local Library"
admin.site.index_title = "Admin Panel"

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid


# Create your models here.
class Genre(models.Model):
	""" Model representing the books genre """
	name = models.CharField(max_length=200, help_text="Enter book genre (e.g. Science Fiction)")

	def get_absolute_url(self):
		return reverse('genre-detail', args=[str(self.id)])

	def __str__(self):
		""" String for representing Model object """
		return self.name



class Language(models.Model):
	name = models.CharField(max_length=100, help_text='Enter original language of the book (e.g. English)')

	def __str__(self):
		return self.name


class Book(models.Model):
	""" Model representing the Books """
	title = models.CharField(max_length=200)
	summary = models.TextField()
	isbn = models.CharField("ISBN", max_length=13, unique=True,
							help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
	language = models.ManyToManyField(Language, help_text="Select a language for this book")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		"""Create a string for the Genre. This is required to display genre in Admin."""
		return ", ".join(genre.name for genre in self.genre.all())

	def display_language(self):
		"""Create a string for the Language. This is required to display language in Admin."""
		return ", ".join(lang.name for lang in self.language.all())

	display_genre.short_description = 'Genre'
	display_language.short_description = 'Language'



class BookInstance(models.Model):
	""" Model representing a specific copy of a book (i.e. can be borrowed from the library) """
	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
	book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)

	status = models.CharField(
		max_length = 1,
		choices = LOAN_STATUS,
		blank = True,
		default = 'm',
		help_text = 'Book Availablity',
	)

	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	class Meta:
		ordering = ['due_back']
		permissions = (('can_mark_returned', 'Set book as returned'),)

	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False

	def __str__(self):
		return f"{self.id} ({self.book.title})"



class Author(models.Model):
	""" Model representing the Authors """
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('died', null=True, blank=True)

	class Meta:
		ordering = ['first_name','last_name']

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

	def get_absolute_url(self):
		return reverse('author-detail', args=[str(self.id)])


class UserToken(models.Model):
	""" Adds extra field to default user model """
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	user_token = models.UUIDField(default=uuid.uuid4, 
								  help_text='Unique token for this user',
								  verbose_name='Token',
								  unique=True)

	def __str__(self):
		return f"{self.user_token}"

catalog/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django import forms as dj_forms
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _

from . import models, forms


#####################
# Home/Landing Page #
#####################

def index(request):
	""" View function for the home page of site """

	# Generate counts of some main objects
	num_books = models.Book.objects.count()
	num_instances = models.BookInstance.objects.count()
	num_authors = models.Author.objects.count()
	num_genres = models.Genre.objects.count()

	# Available books with status 'a'
	num_instances_available = models.BookInstance.objects.filter(status__exact='a').count()

	# Books that contains 'love' word
	num_word_books = models.Book.objects.filter(summary__icontains='love').count()

	# Number of total visits
	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits + 1

	context = {
		'num_books' : num_books,
		'num_instances' : num_instances,
		'num_authors' : num_authors,
		'num_instances_available' : num_instances_available,
		'num_word_books' : num_word_books,
		'num_genres' : num_genres,
		'num_visits' : num_visits
	}

	return render(request, "index.html", context=context)


#####################
# User Registration #
#####################

class UserRegister(UserPassesTestMixin, CreateView):
	model = User
	form_class = forms.SignupForm
	success_url = reverse_lazy('login')

	def test_func(self):
		return not self.request.user.is_authenticated

	def handle_no_permission(self):
		return HttpResponseRedirect(reverse('member-profile', args=[str(self.request.user.pk)]))

	def form_valid(self, form, **kwargs):
		messages.success(self.request, "Sign Up Successful! Please verify your Email before login.")

		form.instance.is_active = 0
		response =  super(UserRegister, self).form_valid(form)

		user_group = Group.objects.get(name="Library Members")
		self.object.groups.add(user_group)

		member_token = self.object.usertoken.user_token
		site_url = f"{self.request.scheme}://{self.request.get_host()}"
		verify_link = reverse("member-verify", args=[str(member_token), str(self.object.id)])
		send_mail(
			subject = "New Member Signup: Email confirmation.",
			message = f"Welcome {self.object.username}, please click the link below \
						to confirm your email address.{site_url}{verify_link}",
			from_email = "lib_admin@mojo.com",
			recipient_list = [self.object.email]
		)

		return response
		

def verifyMemberToken(request, uid, token):
	token_instance = get_object_or_404(models.UserToken, user_token=token)
	user_instance = get_object_or_404(User, id=uid)
	if token_instance and user_instance:
		user_id = token_instance.user.id
		print(user_id)
		if user_id == user_instance.id:
			user_instance.is_active = 1
			user_instance.save()
			messages.success(request,"Email Verified Sucessfully!")
			return HttpResponseRedirect(reverse("login"))
		messages.error(request, "Verification Failed. Invalid Token recieved for the member.")
		return HttpResponseRedirect(reverse("index"))


class UserProfile(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = User
	form_class = forms.ProfileForm

	def form_valid(self, form, **kwargs):
		messages.success(self.request, "Profile Updated Successfully!")
		self.success_url = reverse_lazy('member-profile', args=[str(self.request.user.pk)])
		return super().form_valid(form)

	def form_invalid(self, form, **kwargs):
		messages.error(self.request, "Profile Updation Failed!")
		self.success_url = reverse_lazy('member-profile', args=[str(self.request.user.pk)])
		return super().form_invalid(form)

	def test_func(self):
		return self.request.user.pk == int(self.kwargs['pk'])

	def handle_no_permission(self):
		if self.request.user.is_authenticated:
			messages.error(self.request, "Forbidden Request. Not allowed to acccess other people's profile.")
			return HttpResponseRedirect(reverse('member-profile', args=[str(self.request.user.pk)]))
		else:
			return HttpResponseRedirect(reverse("login"))



#################################
# Generic List and Detail pages #
#################################

class BookListView(generic.ListView):
	model = models.Book
	context_object_name = "library_books"
	template_name = "book_list.html"
	# queryset = models.Book.objects.filter(title__icontains='war')
	paginate_by = 5

	def get_queryset(self):
		query = self.request.GET.get('q')
		if query and query == "available":
			object_list = self.model.objects.filter(bookinstance__status="a").distinct()
			self.paginate_by = ""
		else:
			object_list = self.model.objects.all()
		return object_list

	def get_context_data(self, **kwargs):
		context = super(BookListView, self).get_context_data(**kwargs)
		context['book_type'] = "Latest Books"
		return context


class BookDetailView(generic.DetailView):
	model = models.Book
	template_name = 'book_detail.html'



class AuthorListView(generic.ListView):
	model = models.Author
	template_name = "author_list.html"
	paginate_by = 10


class AuthorDetailView(generic.DetailView):
	model = models.Author
	template_name = "author_detail.html"


class BorrowerListView(LoginRequiredMixin, generic.ListView):
	"""Generic class-based view listing books on loan to current user."""
	model = models.BookInstance
	template_name = 'borrower_list_view.html'
	context_object_name = 'borrowed_books'
	paginate_by = 10

	def get_queryset(self):
		return models.BookInstance.objects.filter(
					borrower = self.request.user
				).filter(
					status__exact='o'
				).order_by(
					'due_back'
				)


class LibrarianListView(PermissionRequiredMixin, generic.ListView):
	""" View for Librarians to manage borrowed books """
	permission_required = 'catalog.can_mark_returned'
	model = models.BookInstance
	template_name = 'librarian_records.html'
	context_object_name = 'librarian_records'

	def get_queryset(self):
		return models.BookInstance.objects.filter(
					status__exact='o'
				).order_by(
					'due_back'
				)


class GenresListView(generic.ListView):
	model = models.Genre
	template_name = 'genre_list.html'
	paginate_by = 10


def genre_details(request, pk):
	genre = get_object_or_404(models.Genre, id=pk)

	if genre:
		books = models.Book.objects.filter(
				genre = pk
			)

		context = {
			'book_genre' : books,
			'genre' : genre
		}

		return render(request, "genre_detail.html", context=context)

	return redirect('index')



##############################
# Librarian (staff) accesses #
##############################

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
	book_instance = get_object_or_404(models.BookInstance, pk=pk)

	if request.method == "POST":
		form = forms.RenewBookForm(request.POST)

		if form.is_valid():
			book_instance.due_back = form.cleaned_data['renewal_date']
			book_instance.save()

			return HttpResponseRedirect(reverse('all-borrowed'))

	else:
		proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
		form = forms.RenewBookForm(initial={"renewal_date":proposed_renewal_date})

	context = {
		"form" : form,
		"book_instance" : book_instance,
	}

	return render(request, "book_renew_librarian.html", context=context)


##################################
# Authors Create, Update, Delete #
##################################

class AuthorCreate(PermissionRequiredMixin, CreateView):
	permission_required = "catalog.can_mark_returned"
	model = models.Author
	fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
	# initial = {"date_of_death" : "20/06/2021"}

	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()

		form = super(AuthorCreate, self).get_form(form_class)
		form.fields['date_of_birth'].widget = dj_forms.TextInput(attrs={"placeholder":" yyyy-mm-dd"})
		form.fields['date_of_death'].widget = dj_forms.TextInput(attrs={"placeholder":" yyyy-mm-dd"})

		return form

	def form_valid(self, form, **kwargs):
		dob = form.instance.date_of_birth
		dod = form.instance.date_of_death

		if dob > dod:
			form.add_error(None, 
				ValidationError(_("Invalid dates - Date of Birth can't be greater than Date of Death."))
			)
			return super().form_invalid(form)
		return super().form_valid(form)


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
	permission_required = "catalog.can_mark_returned"
	model = models.Author
	fields = '__all__'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
	permission_required = "catalog.can_mark_returned"
	model = models.Author
	success_url = reverse_lazy('authors')



################################
# Books Create, Update, Delete #
################################

class BookCreate(PermissionRequiredMixin, CreateView):
	permission_required = "catalog.can_mark_returned"
	model = models.Book
	fields = "__all__"

class BookUpdate(PermissionRequiredMixin, UpdateView):
	permission_required = "catalog.can_mark_returned"
	model = models.Book
	fields = "__all__"

class BookDelete(PermissionRequiredMixin, DeleteView):
	permission_required = "catalog.can_mark_returned"
	model = models.Book
	success_url = reverse_lazy("books")



#####################################
# Borrow/Return Book (BookInstance) #
#####################################

class BorrowBook(LoginRequiredMixin, UpdateView):
	model = models.BookInstance
	fields = ['book', 'imprint', 'due_back']

catalog/templates/author_detail.html
{% extends 'base_generic.html' %}

{% block title %}Author | Library{% endblock %}

{% block addons %}
  <a href="{% url 'author-delete' author.pk %}" class="btn btn-sm btn-warning float-right">&#9938; Delete</a>
  <p class="float-right">&nbsp;</p>
  <a href="{% url 'author-update' author.pk %}" class="btn btn-sm btn-info float-right">&#9842; Update</a>
{% endblock addons %}

{% block content %}
	<h1>Author: {{ author.first_name }} {{ author.last_name }} </h1>
	<p class="text-muted">
		{{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}
	</p><br>

	<div style="margin-left:20px;margin-top:20px">
	    <h4>Books</h4>
	    {% if author.book_set.count == 0 %}
	    	<p class="text-muted">No books available.</p>
	    {% endif %}
	    {% for book in author.book_set.all %}
	    	<p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a><br>{{ book.summary }} </p>
	    	<hr>
	    {% endfor %}
	</div>
{% endblock %}

catalog/templates/author_list.html
{% extends 'base_generic.html' %}

{% block title %}Authors | Library {% endblock %}

{% block addons %}
  <a href="{% url 'author-create' %}" class="btn btn-sm btn-outline-info float-right">&plus; Add Author</a>
{% endblock addons %}

{% block content %}
	<h1>Authors</h1><br>
	{% if author_list %}
		<ul class="list-group list-group-flush">
			{% for author in author_list %}
			<li class="list-group-item">
				<a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }} </a> 
				({{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %})
			</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>Sorry! no authors avaliable in the library.</p>
	{% endif %}
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %} Local Library {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<!-- Add additional CSS in static file -->
	{% block specific %}{% endblock %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
	<div class="container-fluid main-container">
	    <div class="row">
	      <div class="col-sm-2">
	      {% block sidebar %}
	        <ul class="sidebar-nav nav flex-column nav-pills">
	          {% with url_name=request.resolver_match.url_name %}
					<li class="nav-item">
						<a class="nav-link {% if url_name == 'index' %}active{% endif %}"  href="{% url 'index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if url_name == 'books' %}active{% endif %}"  href="{% url 'books' %}">All Books</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if url_name == 'authors' %}active{% endif %}"  href="{% url 'authors' %}">All Authors</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if url_name == 'genres' %}active{% endif %}"  href="{% url 'genres' %}">All Genres</a>
					</li>
				  {% if user.is_authenticated %}
				  		<div class="dropdown-divider"></div>
					  {% if user.is_superuser %}
					  <li class="nav-item"><strong>{{ user.username }} [Admin/Staff]</strong></li>
					  <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a></li>
						<li class="nav-item">
			          		<a class="nav-link {% if url_name == 'analytics_dashboard' %}active{% endif %}"  href="{% url 'analytics_dashboard' %}">Dashboard</a>
			          	</li>
						<li class="nav-item">
							<a class="nav-link {% if url_name == 'all-borrowed' %}active{% endif %}"  href="{% url 'all-borrowed' %}">All Borrowed</a>
						</li>
					  {% elif perms.catalog.can_mark_returned %}
						<li class="nav-item"><strong>{{ user.username }} [Librarian]</strong></li>
						<li class="nav-item">
			          		<a class="nav-link {% if url_name == 'analytics_dashboard' %}active{% endif %}"  href="{% url 'analytics_dashboard' %}">Dashboard</a>
			          	</li>
						<li class="nav-item">
							<a class="nav-link {% if url_name == 'all-borrowed' %}active{% endif %}"  href="{% url 'all-borrowed' %}">All Borrowed</a>
						</li>
					  {% else %}
						<li class="nav-item"><strong>Hello, {{ user.username }}</strong></li>
					  {% endif %}
		          	<li class="nav-item">
		          		<a class="nav-link {% if url_name == 'member-profile' %}active{% endif %}"  href="{% url 'member-profile' user.pk %}">User Profile <b class="float-end">&raquo;</b></a>
		          		<!-- <ul class="submenu dropdown-menu">
		          			<li class="nav-item"><a href="#" class="nav-link">Menu 1</a></li>
		          			<li class="nav-item"><a href="#" class="nav-link">Menu 2</a></li>
		          			<li class="nav-item"><a href="#" class="nav-link">Menu 3</a></li>
		          		</ul> -->
		          	</li>
		          	<li class="nav-item">
		          		<a class="nav-link {% if url_name == 'my-borrowed' %}active{% endif %}"  href="{% url 'my-borrowed' %}">My Borrowed</a>
		          	</li>
		          	<li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
		          {% else %}
		          	<li class="nav-item">
		          		<a class="nav-link"  href="{% url 'login' %}?next={{ request.path }}">Login/Signup</a>
		          	</li>
		          {% endif %}
			  {% endwith %}
	        </ul>
	      {% endblock %}
	      </div>
	      <div class="col-sm-7">
	      	{% if messages %}
		      	{% for message in messages %}
		      		<p class="text-{{ message.tags }}">{{ message }}</p>
		      	{% endfor %}
	      	{% endif %}

	      	{% if perms.catalog.can_mark_returned %}
		      	{% block addons %}{% endblock %}
	      	{% endif %}

	      	{% block content %}{% endblock %}
	      </div>
	      <div class="col-sm-3"></div>
	    </div>
	    <div class="row">
	    	<div class="col-md-2"></div>
	    	<div class="col-md-10">
	    		{% block pagination %}
	    			{% if is_paginated %}
	    				<div class="pagination">
	    					<span class="page-links">
	    						{% if page_obj.has_previous %}
	    							<a href="{{ request.path }}?page={{ page_obj.previous_page_number}}">Previous</a>
	    						{% endif %}
		    					<span class="page-current">
		    						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
		    					</span>
	    						{% if page_obj.has_next %}
	    							<a href="{{ request.path }}?page={{ page_obj.next_page_number}}">Next</a>
	    						{% endif %}
	    					</span>
	    				</div>
		    		{% endif %}
	    		{% endblock %}
	    	</div>
	    </div>
	</div>
</body>
</html>

catalog/templates/book_detail.html
{% extends 'base_generic.html' %}
{% load extra_tags %}

{% block title %}{{ book.title|title }} | Book{% endblock %}

{% block addons %}
  <a href="{% url 'book-delete' book.pk %}" class="btn btn-sm btn-warning float-right">&#9938; Delete</a>
  <p class="float-right">&nbsp;</p>
  <a href="{% url 'book-update' book.pk %}" class="btn btn-sm btn-info float-right">&#9842; Update</a>
{% endblock addons %}

{% block content %}
	<h1>Title: {{ book.title }} </h1>
	<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
	<p><strong>Summary:</strong> {{ book.summary }}</p>
	<p><strong>ISBN:</strong> {{ book.isbn }}</p>
	<p><strong>Language:</strong> {{ book.language.all|join:", " }}</p>
	<p><strong>Genre:</strong> {{ book.genre.all|genre_merge|join:" | " }}</p>

	<div class="section">
		<h2>Reviews</h2>
		<a id="review-btn" href="{% url 'linked_review_form' book.pk %}" class="btn btn-outline-info">Write a Review</a>
		<br>
		<div class="container">
			{% if book.review_set.count == 0 %}
				<p class="text-muted">No reviews avaliable.</p>
			{% endif %}
			{% for review in book.review_set.all %}
				<p class="{% if review.review_polarity == 1 %}text-success{% else %}text-danger{% endif %}"><strong>Review: </strong>{{ review.review }} </p>
				<p class="text-muted"><strong>By: </strong>{{ review.user }} </p>
				<hr>
				{% if review.user == user %}
					<script>document.getElementById("review-btn").remove()</script>
				{% endif %}
			{% endfor %}
		</div>
	</div>
	<div style="margin-left:20px;margin-top:20px">
	    <h4>Copies</h4>
	    {% if book.bookinstance_set.count == 0 %}
	    	<p class="text-muted">No copies available.</p>
	    {% endif %}
	    {% for copy in book.bookinstance_set.all %}
	    	<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
		    	{{ copy.get_status_display }}
		    	{% if copy.status == 'a' %}
			    	<a href="{% url 'borrow-book' copy.pk %}" class="btn btn-sm btn-outline-info float-right">
				    	&plus; Borrow Book</a>
				   {% endif %}
		    </p>
	    	{% if copy.status == 'o' %}
	    		<p class="text-warning"><strong>Due Date: </strong>{{ copy.due_back }}</p>
	    	{% endif %}
	    	<p><strong>Imprint: </strong>{{ copy.imprint }} </p>
	    	<p class="text-muted"><strong>Id: </strong>{{ copy.id }}</p>
	    	<hr>
	    {% endfor %}
	</div>
{% endblock %}

catalog/templates/book_list.html
{% extends 'base_generic.html' %}

{% block title %}Books | Library {% endblock %}

{% block addons %}
  <a href="{% url 'book-create' %}" class="btn btn-sm btn-outline-info float-right">&plus; Add New Book</a>
{% endblock addons %}

{% block content %}
	<h1>{{ book_type }}</h1>
	<a href="{% url 'books' %}?q=available" class="btn btn-sm btn-outline-dark float-right">&#9910; Available Books</a>
	<br>
	{% if library_books %}
		<ul class="list-group list-group-flush">
			{% for book in library_books %}
			<li class="list-group-item"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>Sorry! no books in the library.</p>
	{% endif %}
{% endblock %}

catalog/templates/genre_detail.html
{% extends 'base_generic.html' %}

{% block title %}Genre: {{ genre.name }} | Library{% endblock %}

{% block content %}
	<h1>Genre: {{ genre.name }} </h1>

	<div style="margin-left:20px;margin-top:20px">
	    {% for book in book_genre %}
	    	<p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a><br>{{ book.summary }} </p>
	    	<hr>
	    {% endfor %}
	</div>
{% endblock %}